twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/layout.html.twig']
    globals:
        global: '@App\Service\Globaltwig'

when@test:
    twig:
        strict_variables: true
